name: Release

on:
  push:
    tags:
      - "*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        set -x
        go install github.com/tamalsaha/go-install-gh-actions-demo@v0.0.3+v2021.06.30
        which go-install-gh-actions-demo
        ls -l $(go env GOPATH)/bin
        sudo mv $(go env GOPATH)/bin/* /usr/local/bin
        which go-install-gh-actions-demo
        go-install-gh-actions-demo
